controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_home:
    path: /
    controller: App\Controller\HomeController::index
    methods: ['GET']

convert_pdf:
    path: /convert
    controller: App\Controller\HomeController::convertPdfAction
    methods: ['GET', 'POST']
